version: "3.8"
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fbayinay
      POSTGRES_PASSWORD: 159753
      POSTGRES_DB: comanda
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: comanda@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Comanda159753
    ports:
      - "8089:80"
    depends_on:
      - postgres
  flask:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgres://fbayinay:159753@postgres:5432/comanda
