from .home             import home
from .role             import role_routes
from .action          import action_routes
from .user             import user_routes
from .login            import login_routes
from .table            import table_routes
from .product          import product_routes
from .stock            import stock_routes
from .supplier         import supplier_routes
from .menu            import menu_routes
from .menu_catergory   import menu_category_routes
from .menu_item       import menu_item_routes
from .command          import command_routes
from .command_detail   import command_detail_routes
from .warehouse_movement         import movement_routes
from .receipt          import receipt_routes
from .order           import order_routes